### ISSUE TITLE
Class not found Exception when starting InMoov2 services

### ISSUE THREAD

**Issue by Gleis1234** [MyRobotLab/myrobotlab#1015]
When starting InMoov2 services several java CassNotFound or ClassCastException errors happen.

**To Reproduce**
1. On InMoov2 WebGui click GO icon.
2. Open a InMoov2 configuration e.g. InMoov2/RightSide

**Expected behavior**
The configuration is loaded and gestures can be executed.

**Screenshots**

**Desktop (please complete the following information):**
 - Kubuntu 20.04 
 - Chrome 
 - 97.0.4692.71

**Additional context**
[InMoov2.log](https://github.com/MyRobotLab/myrobotlab/files/7914378/InMoov2.log)
I downloaded Nixie from http://build.myrobotlab.org:8080/job/myrobotlab/job/develop/lastSuccessfulBuild/artifact/target/myrobot
lab.zip and installed it. Version is 1.1.701

**Comment by kwatters** [comment]
We saw this error recently, it might be caused by some bad data in your .ivy2 cache.  
try deleting your .ivy2 cache and re-run the install.  This will force a fresh download of all the dependencies.
The ivy2 cache is normally located in your home directory   
rm -rf ~/.ivy2  

Let us know how it goes!

**Comment by Gleis1234** [comment]
This seems to be it. The .ivy2/cache holds data of a previous version. The GUI starts now. Now there appears a new exception, but it seems it depends on the wrong serial port, which are default for windows, not for unix. I have to look for that.
I close this issue. Maybe I have to open a new one.
Thank you for support.
