### ISSUE TITLE
VinMoov shouldn't use the mappings applied to the real servos

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#1026]
**Describe the bug**
VinMoov shouldn't use the mappings applied to the real servos because when my real robot is at "rest", VinMoov "rest"  looks totally wrong.

**To Reproduce**
1. Launch a preset config of InMoov2 and watch the position of VinMoov, that's the "rest" position
2. Now start to adapt the mappings to your real robot servos
3. Say to the chatbot "rest"
4. Your real robot will take a normal "rest" position, while VinMoov will be completely offset.

**Expected behavior**
VinMoov has it's own mappings, therefore real servo mappings shouldn't be applied to it.

**Screenshots**
This is the proper "rest" position for real robot and VinMoov:
![Capture d’écran 2022-01-30 183157](https://user-images.githubusercontent.com/8484551/151710442-2778cd7e-b3a0-4338-bf1c-3a94d20d0161.png)

This is the "rest" position of VinMoov after applying the mappings to my servos:
![Capture d’écran 2022-01-30 181314](https://user-images.githubusercontent.com/8484551/151710345-5a787362-9073-4258-8811-cfbc28e9b9b4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Browser chrome
 - Version mrl [1.1.708]
 - Version InMoov [465]

**Comment by supertick** [comment]
TimeEncoder now publishes inputs - after lengthy discussions :) 
Fix in 1.1.822
