### ISSUE TITLE
Mrl.org

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#103]
Not responding. Is it m'y crappy gsm signal or : https://youtu.be/sonLd-32ns4

**Comment by MatsMRL** [comment]
I get 404 or ERR_CONNECTION_REFUSED when trying to connect to
http://myrobotlab.org/

Guess the server or connection is down / overloaded

2017-08-22 21:39 GMT+02:00 Anthony <notifications@github.com>:

**Comment by hairygael** [comment]
Hello all,
Same error 404 for me.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-08-22 21:55 GMT+02:00 Mats <notifications@github.com>:

**Comment by kwatters** [comment]
site is back up closing this issue.
