### ISSUE TITLE
Remove all sensor stuff from Servo

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#104]
Servos are not Sensors!!!!

This ticket is to clean up all of the servo stuff.  A finger sensor should be a new service in MRL.. not just wedged into the existing servo service.

Servo services control servos!

**Comment by moz4r** [comment]
Ok . Idea was to set a torque to servo by adding a new method.
I Will try to migrate things.
New generic service or inmoov hand mod ?

**Comment by kwatters** [comment]
There should be a "Sensor" service that handles this. so a new service.  but we want a code freeze until Manticore is released.  

so. please no new check-ins for the myrobotlab project until after that's done.

**Comment by supertick** [comment]
We need Testing ! ..   and since we are in the mode of testing & fixing bugs, we should create unit tests - let the machine test all these things we have fixed in the past ... 

We can use the tickets marked as closed as a reference to create unit tests !

**Comment by supertick** [comment]
servos are being auto-tested, sensor code was removed, lots of refactoring
