### ISSUE TITLE
Neopixel should turn off

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#1040]
**Describe the bug**
When shutting down MRL, Neopixel doesn't turn off

**To Reproduce**
1. Start a neopixel service
2. Light it up
3. Turn off MRL

**Expected behavior**
One would expect MRL to stop the animation and clear leds, otherwise, it means you need to pull the plug off.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 64
 - Chrome
 - Version [e.g. 1.1.731]

**Comment by supertick** [comment]
fixed in 1.1.733
