### ISSUE TITLE
ringtone issue while speakBlocking

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#1053]
**Describe the bug**
With Nixie some speakBlocking text are being played with a ringtone when played in Windows 10

**To Reproduce**
1. Test in Windows 10 64.
2. Go to InMoov2 UI 
3. Turn ON mouth button with LocalSpeech selected
4. In python tab execute: i01.speakBlocking("This is where my builder downloaded my files.")
5. Hear the ringtone while tts is playing
6. Try now to execute this tts and there is no ringtone: i01.speakBlocking('This is where my builder downloaded my file.')
7. Note there is a "s" removed at the end of text when it doesn't make the ringtone.

**Expected behavior**
There shouldn't be that ringtone. I am not sure it is only with the tts, because I hear the ringtone also sometimes when starting some services where there is spoken text. I have tried with two different pc and get the same ringtones. The ringtone is a system bell.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [1.1.758]

**Comment by supertick** [comment]
Heh ... I did here a slight buzz after when I tried
![image](https://user-images.githubusercontent.com/1266144/178147730-13fd693f-c777-41bc-b8bf-108d86434b90.png)
but this is completely LocalSpeech problem not a MRL one.  You would need to do a bug against tts.
