### ISSUE TITLE
Service Pages for Services !

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#108]
The following services need Service Pages.
Can you help ?

Agent 
AndroidSpeechRecognition 
Arm 
AzureTranslator 
Blocks 
BoofCv 
Chassis 
ChessGameManager 
CsvConnector 
Database 
DatabaseConnector 
DocumentPipeline 
EddieControlBoard 
FileConnector 
GoPro 
HtmlFilter 
HtmlParser 
HttpClient 
ImageDisplay 
ImapEmailConnector 
InMoovEyelids 
Incubator 
InverseKinematics3D 
JMonkeyEngine 
JavaFxGui 
JavaScript 
Lex 
Lidar 
Log 
Mail 
MimicSpeech 
MobilePlatform 
MotorPulse 
NaturalReaderSpeech 
Node 
OculusDIY 
OpenWeatherMap 
Picaxe 
PickToLight 
Pir 
Piston 
Polly 
RSSConnector 
Rekognition 
Ros 
Security 
SegmentDisplay 
SerialRelay 
ServoOrchestrator 
Shoutbox 
Sprinkler 
Sweety 
SwingGui 
TarsosDsp 
TestCatcher 
TestThrower 
TextTransform 
Tutorial 
VirtualDevice 
VoiceRss 
Webcam 
Wii 
WiiBot 
WiiDar 
WikiDataFetcher 
XMLConnector 
YahooFinanceStockQuote 
_TemplateService

**Comment by moz4r** [comment]
just a question, how to create a Service Page

**Comment by supertick** [comment]
Good question .. you have to be a content admin @ myrobotlab.org
I have anointed you so ...
![knight](https://user-images.githubusercontent.com/1266144/29756376-438936da-8b58-11e7-8f4a-e70c732d2322.jpg)
You should now have capability of making a service page when you press "create content"
![service](https://user-images.githubusercontent.com/1266144/29756423-b88a5c3e-8b58-11e7-9c08-7d29b4ce00a7.png)

I tried to standardized the format with forms, but it did not work so well. When you save it you have to go in and edit it again and make sure the "url" is  /service/{serviceName}  vs /content/{serviceName} - and then webgui & swinggui and other things will understand it as "help" for a service..

**Comment by moz4r** [comment]
Great ! It is a good solution to test and discover all services !
Lets feed mrl bible !
todo list ( near the top )

**Comment by supertick** [comment]
Thanks Moz4r !!! - Lots of bible pages
Your a dedicated monk ;)
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwiqv4Pf56PWAhUC0GMKHaYgAQwQjRwIBw&url=http%3A%2F%2Fwww.victorianpicturelibrary.com%2Fdownloads%2Fmedieval-monk-calligrapher%2F&psig=AFQjCNGp0qeoRf9E4kTx2pm117iiMHYqQw&ust=1505448714856383

**Comment by supertick** [comment]
Spectacular mopping from moz4r .. lots of new very nice scripts.  Service page scripts auto-magically added to Service pages.  Good Work ...goodtimes....
