### ISSUE TITLE
Removal of meaningless Junit Tests

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#110]
There are many empty shells of junit which were generated (some by me) - these should be removed, to clean the clutter.  Additionally, they give the "impression" that a service is being tested when it is not...

As a general rule, testing interfaces are of more worth than testing individual services.   For example, if we test all the functions of SpeechSynthesis for all classes which implement that interface - we are doing much more meaningful testing with less code !

**Comment by kwatters** [comment]
For nixie release, if we have a junit test that is useless (doesn't assert anything) we should ignore it.  If we have a unit test that has no actual code in it, we should delete the file.

**Comment by kwatters** [comment]
Seems to be an error in the logging test related to my initial pull request.  i'm going to comment out the failing part of the test with a comment / TODO..

**Comment by kwatters** [comment]
I think the essence of this ticket has been handled.  We can triage better code coverage in a different ticket.
