### ISSUE TITLE
MarySpeech - needs to cache spoken text

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#111]
MarySpeech should cache generated speech files the same as other SpeechSynthesis services.  It will improve performance, and reduce resource load on cpu.

If the file is cached, AudioFile will also do the threading correctly.  

If AudioFile + caching is not used the threading should be as follows,
given 2 utterances

maryspeech.speak("some sentence")
maryspeech.speak("another sentence")

without speakBlocking neither should block HOWEVER, they should be played sequentially, and the second should not start until the first is done .. this is achieved with queue'ing on a queue and blocking the thread which is processing the queue..

preferably this is done on a separate queue than the inbox, since the inbox is used for command & control too.

**Comment by LunDev** [comment]
About caching:
This is more complicated with MaryTTS as with other TTS-Services.
With Mary you do not only need to seperate the voice files by language, but also by effect(-combinations).

I agree, it should be done : )

**Comment by supertick** [comment]
Doesn't need to be done for Maticore release, removing from project, but keeping open
