### ISSUE TITLE
Tooling for code quality improvement

### ISSUE THREAD

**Issue by holgerfriedrich** [MyRobotLab/myrobotlab#1121]
When I started to work with the MRL codebase using my favourite development IDE (MS Code), I found a few things which could be improved. There seem to be files with inconsistent line endings (like pom.xml), a lot of unused imports in Java files, etc.

I have some time during my robot is printed ;-), so I could support in cleaning things up, add automated tools like spotless, spotbugs/pmd, etc.

Would you be willing to merge such PRs?
WDYT?

**Comment by AutonomicPerfectionist** [comment]
@holgerfriedrich that sounds great; I was thinking about cleaning up the code just the other day. I'm sure any PRs made would be gladly welcomed
