### ISSUE TITLE
MavenWrapper does not select correct scope of dependency if it's found at a different scoep earlier

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [MyRobotLab/myrobotlab#1137]
**Describe the bug**
When MavenWrapper generates the pom.xml, it loops over all of the services to find their dependencies. It will then determine what their scope should be by looking at the `includeServiceInOneJar()` property. If it finds a dependency that was already written, it will skip the dependency. However, if the first one had a different scope, then it will not be updated to match the scope of the skipped one.

**To Reproduce**
1. Add Jackson dependencies to RuntimeMeta
2. Generate pom.xml with MavenWrapper
3. Observe the jackson dependencies still listed as `provided` due to MQTT being processed first

**Expected behavior**
If a dependency that was already written is found but with a higher scope, then the scope should be updated.

**Comment by supertick** [comment]
I think I'm starting to understand.
its not a higher scope - you just mean specifically since MQTT's dependencies collided with Runtime, they were stolen away.

If your intent is to package the deps in a build with Runtime, they should simply be removed from declaring them elsewhere like MqttMeta etc..

**Comment by AutonomicPerfectionist** [comment]
I suppose that's a simple fix, but then if we ever remove Jackson from the framework stuff it would break all the services. I found where the issue lies (MavenWrapper in createPOM()) and it should be pretty easy to fix, just need a simple preprocessing stage to loop over dependencies and remove duplicates, keeping the one with the highest priority scope (i.e. packaged-in is higher priority than provided), then the writing stage doesn't have to worry about duplicates
