### ISSUE TITLE
Human body masks with sensors to track and record movements.

### ISSUE THREAD

**Issue by askmurphy** [MyRobotLab/myrobotlab#1145]
What about this: a face-mask with sensors which can be put on your face and an option to record all your face movements to a MRL script?

I have seen this for hand movements already. Same thing for the whole body 😀

Examples:

https://create.arduino.cc/projecthub/laurencemlai/diy-glove-controlled-robotic-hand-ff5d63

https://youtu.be/6bxZyTi6m-4

https://www.electroniclinic.com/human-posture-monitoring-using-flex-sensor-arduino-arduino-biomedical-project/

**Comment by supertick** [comment]
probably connect to a quest 2 and hand controllers first

**Comment by supertick** [comment]
![image](https://user-images.githubusercontent.com/1266144/229383480-1607da29-2a9c-4a48-bc94-43fcc5fc560b.png)

**Comment by supertick** [comment]
https://github.com/MyRobotLab/myrobotlab/raw/develop/doc/inmoov-quest2.gif
