### ISSUE TITLE
Rekognition service does not implement minimum confidence level setter

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [MyRobotLab/myrobotlab#1163]
In the Rekognition service there is a method called `setMinConfidence()` that looks to be intended as a setter for the minimum confidence level property, however the method body is empty.

Here:
https://github.com/MyRobotLab/myrobotlab/blob/7e0fa471753461cd209d4c0700217b1a65255212/src/main/java/org/myrobotlab/service/Rekognition.java#L57-L59

**Comment by supertick** [comment]
Heh ... did you want to implement it ? :)

**Comment by AutonomicPerfectionist** [comment]
Yeah, mainly made the issue to remind me to fix it cause I was on the bus at the time
