### ISSUE TITLE
error message localhost

### ISSUE THREAD

**Issue by snnusta** [MyRobotLab/myrobotlab#1238]
http://localhost:8888/api/messages?user=root&pwd=pwd&session_id=2309adf3dlkdk&id=webgui-client&X-Atmosphere-tracking-id=1b557381-44e1-4b33-9977-1561387352ac&X-Atmosphere-Framework=2.3.0-javascript&X-Atmosphere-Transport=sse&X-atmo-protocol=true

**Comment by supertick** [comment]
for web sockets ?

**Comment by supertick** [comment]
not much detail here
