### ISSUE TITLE
AudioFile service play actual stream

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#1250]
Currently the AudioFile service downloads any internet sound file and will cache and play it.
However, this will not work with audio streams.
An example http://direct.fipradio.fr/live/fip-midfi.mp3 from lecagnois
In this case, the read buffer of Http service should go directly to the audioFile in a new stream thread.

**Comment by hairygael** [comment]
There is another way to stream radio, is to use the oob tags in the AIML files if required.

**Comment by supertick** [comment]
how ?   ... is python streaming a real stream or is it downloading a file and playing ?

**Comment by hairygael** [comment]
It's directly the browser that streams. The aiml use webgui service to startBrowser with the link of the radio and that's it. The only pb is that webgui service doesn't seem to have stopBrowser. I have put a gif on discord showing it.

**Comment by hairygael** [comment]
https://discord.com/channels/887362610360643664/1009121322133098518/1070412325795930182

**Comment by supertick** [comment]
handling all different streams from the web is non trivial .. perhaps a BDD ticket for VLC
