### ISSUE TITLE
Simulator not working

### ISSUE THREAD

**Issue by frankstolp80** [MyRobotLab/myrobotlab#1268]
when starting simulator get blank on version myrobotlab-1.1.1061 is working after version myrobotlab-1.1.1069 it not working i tryd the last version myrobotlab-1.1.1071 still blank

![errors](https://user-images.githubusercontent.com/131405482/233481736-b71d29f4-0a01-45b4-8fc3-4436b54dcd95.jpg)
![simulator](https://user-images.githubusercontent.com/131405482/233481753-d733e059-49f2-4958-ae52-76668b28ceb0.jpg)

**Comment by supertick** [comment]
It looks more like your missing InMoov2 models - and this occurred because of maven repo shifting.
You can try this, on windows delete the .ivy2 located go to C:\Users\{yourUser}\
Start myrobotlab in a fresh directory.

**Comment by frankstolp80** [comment]
@supertick i deleted the .ivy2 directory but after restart still blank the is what i get when it is on
![errors2](https://user-images.githubusercontent.com/131405482/233494383-8eea35a7-ce78-4c0b-882e-2b9639a2a12e.jpg)

**Comment by supertick** [comment]
Looks worky for me .. :thinking: 
![image](https://user-images.githubusercontent.com/1266144/233495018-81dbd5dd-5963-41ea-9df7-bb0bb8086cf1.png)

**Comment by supertick** [comment]
any errors in the myrobotlab-install.log ?

**Comment by frankstolp80** [comment]
this is the myrobotlab-install.log

[myrobotlab-install.log](https://github.com/MyRobotLab/myrobotlab/files/11296801/myrobotlab-install.log)

**Comment by AutonomicPerfectionist** [comment]
Can you check if you have an `InMoov2` directory in the folder above where you installed MRL?

**Comment by frankstolp80** [comment]
it is in the above directory see screenhot i copyd the imoov2 the mrl\Inmoov2  and it works now
my sinstall directory is mrl\myrobotlab-1.1.1071a\...
![Uploading error3.jpg…]()

**Comment by supertick** [comment]
screenshot was not successful, ah .. you manually copied and now its worky ?

**Comment by frankstolp80** [comment]
@supertick it is in the above directory see screenhot i copyd the imoov2 the mrl\Inmoov2 and it works now
my sinstall directory is mrl\myrobotlab-1.1.1071\...

![error3](https://user-images.githubusercontent.com/131405482/233667888-ba0e710c-7e0e-42df-b94a-359695569ae6.jpg)
![Naamloos4](https://user-images.githubusercontent.com/131405482/233667893-ffa81d90-4615-4e15-a1ac-a0361edf081c.jpg)

**Comment by AutonomicPerfectionist** [comment]
As I was afraid of, that InMoov2 directory is not actually supposed to be there. @supertick we've seen multiple instances of that directory appearing now, I think we should investigate why it's being created there

**Comment by supertick** [comment]
yeah @frankstolp80 .. do you know how the InMoov2 directory got there ?
when myrobotlab starts and that directory exists at that location it thinks int in "develop mode" ... which is probably not your intention.   If that directory is removed, myrobotlab will use the InMoov2 directory that was installed when it starts up.

**Comment by supertick** [comment]
@AutonomicPerfectionist not sure how the directory is being created, but the safe thing is removing all code that supports this "special" dev mode and use git submodules correctly.

**Comment by frankstolp80** [comment]
@supertick  after a fresh install of myrobotlab it it creates the directory or how can i turn off the develop mode when i delete the directory it and restart it creates directory again than emty see screenshot

![Naamloosz](https://user-images.githubusercontent.com/131405482/233671250-c52dab83-5d61-4b1c-8e6a-20f10038e32a.jpg)

**Comment by supertick** [comment]
checking ....

**Comment by frankstolp80** [comment]
i got this error also

![Naamloosv](https://user-images.githubusercontent.com/131405482/233671931-35f63a9c-30f8-4edb-a425-5a0e1098ee49.jpg)

**Comment by supertick** [comment]
i can't seem to recreate the problem using 1.1.1071
I don't get InMoov2 appearing  .. :thinking: 
![image](https://user-images.githubusercontent.com/1266144/233673300-30863875-950f-4edf-ba21-1a445581c0ef.png)

**Comment by frankstolp80** [comment]
the opencv has also errors wheni try to add filters see log

[myrobotlab.log](https://github.com/MyRobotLab/myrobotlab/files/11297671/myrobotlab.log)

**Comment by frankstolp80** [comment]
it works now
