### ISSUE TITLE
SwingGui Freeze

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#127]
![image](https://user-images.githubusercontent.com/18124594/30697750-53313452-9ee0-11e7-86d5-0ba80a617f49.png)

Sometime when we cook some ingredients, swingGui freeze.
The only thing to do for unfreeze is resize the window, or undock tab panel.
This is a freeze test to understand : https://github.com/MyRobotLab/pyrobotlab/blob/develop/home/moz4r/Test/freezeTest.py

**Comment by supertick** [comment]
Fixed I believe in build 2525

Nice Script Moz4r !!! 

![thaw](https://user-images.githubusercontent.com/1266144/30710962-03838730-9ebc-11e7-9455-2c86251b12b4.jpg)
