### ISSUE TITLE
i01.head.jaw.yml help

### ISSUE THREAD

**Issue by frankstolp80** [MyRobotLab/myrobotlab#1281]
the jaw goes to 180 in rest

maxIn: 26.0
maxOut: 91.0
minIn: 2.0
minOut: 0.0
peers: null
pin: '26'
rest: 0.0

![fff](https://user-images.githubusercontent.com/131405482/235782778-274d9fd8-cc8c-48b7-a4cd-97296c4b8403.jpg)

fixed
i remaned the config directory in resource\InMoov2\config

**Comment by supertick** [comment]
:+1:
