### ISSUE TITLE
Python ( or something else borked ) ?

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#129]
This issue occur if I start Python service from another.
If I delete .myrobolab folder, this seem fix. But is there something else hidden ?

![image](https://user-images.githubusercontent.com/18124594/30776630-3fe98982-a0aa-11e7-97fa-f9f421e52f82.png)

**Comment by supertick** [comment]
Ya something in Python serialization changed.. if it occurs to anyone I think deleting the .myrobotlab directory will work
