### ISSUE TITLE
runtime.setLogLevel borked

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#132]
Seem `runtime.setLogLevel("ERROR")` have no effect. or it is me

**Comment by supertick** [comment]
looking into it a little - it appears executing python scripts flips it back to INFO - setting it by swing gui (runtime->logging->setLogLevel->ERROR) works until another python script is executed..

**Comment by supertick** [comment]
further investigation - it appears that something with publishing to stdout changes log level .. I can get it to switch back to INFO or DEBUG when I do activity in the cli too...  cli & python both publish to stdout

**Comment by supertick** [comment]
issue was in Python's java console Console.java - it setLevel("INFO") - removed it
