### ISSUE TITLE
错误: 找不到或无法加载主类 org.myrobotlab.service.Runtime 原因: java.lang.ClassNotFoundException: org.myrobotlab.service.Runtime

### ISSUE THREAD

**Issue by mrz5802** [MyRobotLab/myrobotlab#1326]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by supertick** [comment]
get a later version https://build.myrobotlab.org:8443/job/myrobotlab/job/develop/1201/artifact/target/myrobotlab.zip

**Comment by mrz5802** [comment]
Thank you, it has been resolved
