### ISSUE TITLE
Analog pin A6 and A7

### ISSUE THREAD

**Issue by Dom1416** [MyRobotLab/myrobotlab#133]
With arduino nano, i can't read analog pin A6 and A7.

I would like used A4 and A5, but it is used for I2C bus.

**Comment by supertick** [comment]
Refer to - http://myrobotlab.org/content/silly-nano for details

**Comment by wilcovantoorn** [comment]
Can we lift this to ogre or is it of thus importance to fix in nixie ? Dom did find a workaround and it is documented in the Silly Nano blog post.
Just thinking out loud.

**Comment by supertick** [comment]
I'd call it an obscure hardware detail, with known solution if your ready to hack it, or if arduino headers take care of it.
Closing.
