### ISSUE TITLE
I2C servo wont enable after disabled

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#136]
tested on raspi

https://github.com/MyRobotLab/pyrobotlab/blob/develop/service/Adafruit16CServoDriverPi.py

**Comment by moz4r** [comment]
I got my hands on the hive, need to deal with other things related..
> remember servo position at restart
> add servo event to i2C servo driver
> set double for every servo things ( sometime conditions failed because 170 != 170.0001 ... )
> fix fake messages sent by servo events ( servo is really moving > isMoving==False )
etc ...

**Comment by supertick** [comment]
Heh.. "hands on hive" ... Every day my RESPECT depends for you moz4r !

**Comment by juergmaier** [comment]
hands on hive?? could you elaborate on this idiom?  and your respect would rather deepen then depend?
sorry, not blaming just not beeing able to follow.

**Comment by moz4r** [comment]
Hi mates ! What I meant is I wanted to fix one thing, I was thinking of something simple, but I encountered some obstacles... 
Now I think everything fixed , yehhh : 

- Now , when you close mrl servo position is "recorded" inside json. When you open it again. So no more fullspeed movement. Not related to I2C, general thing.
- I2C is worky now like Arduino controller about servo events ( Autodisable, isMoving, Blocking moveto ... )

![image](https://user-images.githubusercontent.com/18124594/32273737-ee2ff900-bf03-11e7-8f03-127ab6573f62.png)

**Comment by supertick** [comment]
@juerg .. yes, deepen. Inaccurately, autocorrected ... I blame the robot in my phone.
