### ISSUE TITLE
ProgramAbGui - Reload Session button

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#140]
Ray says,

> Small bug with the ProgramAB service GUI. I'm launching and starting the service using a python script, however the GUI still has the Start Session button instead of the Reload Session button

**Comment by moz4r** [comment]
Fixed

**Comment by Sebchko** [comment]
Hello! Just to say that the reload button don't work on my config.
(before the update, this button was labeled "start session" at first but the text changed to "reload" after the first use. )
@+

**Comment by moz4r** [comment]
Hi if you change the username this will reload the session with the new username. But maybe we need a restart buton

**Comment by Sebchko** [comment]
Don't know if we need it, but I was using it :)
, I make a vocal comment to reload the session so ... no worries
(restarting MRL even in "light mode" to test any small change in the aiml is really a pain in the ass)

**Comment by moz4r** [comment]
you right , a raw restart will be useful, few mods pushed : 

restart chatbot : just restart engine
restart w/o aimlif : restart by using aiml at startup ( useful for real time debug )
reload session : change username ( for predicates )

no more troubles in the ass ahahaha
