### ISSUE TITLE
No GUI for Nixie2 with Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by Gleis1234** [MyRobotLab/myrobotlab#1429]
**Describe the bug**
Starting myrobotlab.sh no GUI opens.

**To Reproduce**
1. Go to $HOME/[myrobotlab.log](https://github.com/user-attachments/files/16839251/myrobotlab.log)
2. start myrobotlab.sh

**Expected behavior**
Opening a GUI in browser with Nixie2 content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Browser firefox, chrome
 - Version 129.0.2, 128.0.6613.113

**Additional context**

**Comment by supertick** [comment]
I often run it on 22.04,
what does the myrobotlab.log say ?

**Comment by Gleis1234** [comment]
The logfile gives me no idea what's going wrong. Logfile added. Maybe anyone will find something.
[myrobotlab.log](https://github.com/user-attachments/files/16921123/myrobotlab.log)

**Comment by supertick** [comment]
I see this ..
20:58:35.010 [main] WARN c.m.n.BareBonesBrowserLaunch [BareBonesBrowserLaunch.java:37] graphical browser requested but currently no display
Are you starting in a ssh session ?

**Comment by supertick** [comment]
no display means you don't have a desktop like Xorg etc... are you trying to use the gui from a remote machine ?  If so, you need to open port 8888 up on the ubuntu firewall if its running, you also need to know the ip address of the host your running mrl on and use that in the browser

**Comment by Gleis1234** [comment]
No, I start from the console on the desktop of a Kubuntu installation. The Plasma environment of Kubuntu runs under Xorg. In the meantime I am going back to 22.04

**Comment by supertick** [comment]
Do you have a browser on the desktop ?
If so, have you tried manually going to http://localhost:8888 ?

**Comment by Gleis1234** [comment]
No chance I purged the system.

Am 8. September 2024 14:48:41 MESZ schrieb GroG ***@***.***>:

**Comment by Gleis1234** [comment]
Back in 22.04 everything works as expected.

**Comment by supertick** [comment]
From the logs it looks like MRL started without a problem on your Plasma environment of Kubuntu.
MRL is a web server, so I believe you could use it in that environment.  The only problem I saw, is MRL did not know how to "automatically" spawn a browser to open the URL .. which could be done manually or remotely.
Just a FYI if you want to go back to using Plasma environment of Kubuntu.
