### ISSUE TITLE
Issue with NaturalReaderSpeech mixed up voices

### ISSUE THREAD

**Issue by CheekyMonkey** [MyRobotLab/myrobotlab#145]
Issue with NaturalReaderSpeech mixed up voices

Commentary here for reference : https://github.com/MyRobotLab/myrobotlab/commit/d7ae81c867c14465752cd36b0d856d365e91dcad

Python test script [here](https://github.com/MyRobotLab/pyrobotlab/blob/develop/home/CheekyMonkey/naturalreaderspeech-v2-test.py)

Reference video [here](https://www.youtube.com/watch?v=JpMQ6OwDyTw&feature=youtu.be)

![naturalreaderspeech screenshot 2017-12-13 14 54 15](https://user-images.githubusercontent.com/537672/33945058-d70dcac6-e015-11e7-940e-875e1f679c63.png)

**Comment by hairygael** [comment]
As you can see I tried to reformate the correct name list with numbers in a
logic order in a attempt to fix the mixed up voices, but that didn't do the
trick.
I have also tried to find on NaturalReaderSpeech site the liste with
numbers which would indicate the correct numbers, but my knowledge in that
field has limits.
Hopefully a charitable soul will come to rescue.
:)

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-12-13 15:57 GMT+01:00 Acapulco Rolf <notifications@github.com>:

**Comment by CheekyMonkey** [comment]
Thanks Gael, let's wait and see :)

**Comment by moz4r** [comment]
charitable soul in progress

**Comment by hairygael** [comment]
:)
Keep me informed!
Because for now when I want the Ryan voice, I get Tim's voice instead (I'm
not even sure it's really Tim, though)

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-12-16 1:14 GMT+01:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
dig into code, it if funny natural use 2 external providers. Amazon Polly and .. Ibm Watson . I let you know

**Comment by moz4r** [comment]
Hacked, this message will autodestruct .
Worky ( still no guaranties about longevity, but no magic here, external providers used by natural, we can borg them later if it not done already ) , 

http://myrobotlab.org/service/NaturalReaderSpeech?branch=develop

**Comment by CheekyMonkey** [comment]
Hi moz4r

Seems still noworky, for me at least (build 2673 )
All voices appear to return the same male voice

test script [here](https://github.com/MyRobotLab/pyrobotlab/blob/develop/home/CheekyMonkey/naturalreaderspeech-v2-test.py)
