### ISSUE TITLE
MyRobotLab moves to Maven

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#153]
Make necessary changes to enable Maven builds.  

Manage dependencies via Maven & new MyRobotLab Artifactory service.

Change directory structure to align with Maven conventions.

Make Jenkins Pipeline build & deploy new snapshot build from develop branch

Change runtime dependency embedded Ivy to handle new dependencies

**Comment by supertick** [comment]
Kwatter and I tag-teamed this !

Make necessary changes to enable Maven builds.

~~Manage dependencies via Maven & new MyRobotLab Artifactory service.~~

~~Change directory structure to align with Maven conventions.~~

Make Jenkins Pipeline build & deploy new snapshot build from develop branch

~~Change runtime dependency embedded Ivy to handle new dependencies~~

**Comment by kwatters** [comment]
The develop branch now uses Maven to run in eclipse, and maven can also produce a build, however, runtime installation of services and their dependencies is still no worky.

**Comment by supertick** [comment]
Works ! we also have the "latest" link hooked up and a version number from Jenkins !
Starting with 1.1.37 -  Rockn !

**Comment by hairygael** [comment]
Great work!!
I have just downloaded the latest MRL and will test.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-04-10 15:19 GMT+02:00 GroG <notifications@github.com>:
