### ISSUE TITLE
IntegratedMovement - dependencies or service name is incorrect

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#157]
The IntegratedMovement service has dependencies of InMoov - if its a service only for InMoov it should have InMoov dependencies and be renamed InMoovIntegratedMovement.  If its to be a more general service, then the code needs to be refactored and the dependencies dropped.

**Comment by hairygael** [comment]
Mmmh,
Hopefully a nice Elve is going to help on that because I wouldn't know
where to start!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-01-09 15:39 GMT+01:00 GroG <notifications@github.com>:

**Comment by supertick** [comment]
Calamity was the awesome wizard who created it ...
So, this was to give him a chance to decide which path to take ..
If he's too busy, then I'll probably just rename it to InMoovIntegratedMovement

**Comment by Calamity01** [comment]
dependency for inMoov should be removed as integratedMovement is not just for inMoov and don't use inMoov in his code. I don't remember why it was added,
