### ISSUE TITLE
InMoov.zip output from build needs to be small-case (inmoov.zip)

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#160]
Having issues with pom.xml & artifactory resolving InMoov.zip - I "think" it has to do with artifactId & artifactory being small case when the file is imported (might be a convention)

Linux systems are very case sensitive, so if all else fails pretend the Cap key doesn't exist ! :D

**Comment by moz4r** [comment]
pushed ( just updated build.xml from Inmoov repo ) . is it enough ?

**Comment by supertick** [comment]
BooYa .. maven likes it !
