### ISSUE TITLE
Tag Word added to Abstract SpeechRecognizer

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#162]
AbstractSpeechRecognizer should have the ability to add a "Tag" word which changes the context the robot so that it knows its in an "attentive" state.   The duration of the state could "timeout" if no recognized command or activity is found.  

It's certainly more inline with the popular "Personal Assistant" applications such as Alexa & Google Home.

See more details here :
http://myrobotlab.org/content/voice-command-trigger-robot-name-only

**Comment by kwatters** [comment]
I think @moz4r   added some stuff for this with the lock out grammar commit...  So this might be done?  I'm not sure.

**Comment by supertick** [comment]
No its not done.  There is a time involved and it needs to be done consistently the same in a speech recognizers (ie it needs to be done in AbstractSpeechRecognizer)

Moving to Ogre..

**Comment by supertick** [comment]
This was implemented in AbstractSpeechRecognizer
Its called WakeWord
