### ISSUE TITLE
Mouthcontrol Sync issue

### ISSUE THREAD

**Issue by DSBRobotics** [MyRobotLab/myrobotlab#163]
MOUTHCONTROLJAWTWEAK=True
Will not continue loading MRL.

**Comment by supertick** [comment]
@DSBRobotics  - do you send us a noWorky ?

**Comment by DSBRobotics** [comment]
I have, twice. One my tablet and one for my laptop.

**Comment by DSBRobotics** [comment]
Any ideas or do you need more info?

**Comment by moz4r** [comment]
Hi DSB ! There is a little bug, please look at this line Inside head.py file. 

https://github.com/MyRobotLab/inmoov/blob/master/InMoov/skeleton/head.py#L127

Just change set**D**elays by setdelays

**Comment by DSBRobotics** [comment]
Need a little more explanation, I’m not a programmer, working on it. So do I change “.setDelays” to “setdelayes “ or add??
Thanks for your patience

**Comment by hairygael** [comment]
Thanks Anthony for spoting this bug!!
@DSRobotics:
Replace "setDelays" by "setdelays".

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-02-16 16:43 GMT+01:00 DSBRobotics <notifications@github.com>:

> Need a little more explanation, I’m not a programmer, working on it. So do
> I change “.setDelays” to “setdelayes “ or add??
> Thanks for your patience
>
> Sent from my iPhone
>

**Comment by DSBRobotics** [comment]
Thanks for helping. Correction did allow program to continue and load but did not fix delay in mouth movements. Now as talking just holds mouth open, no movement. Tired changing sets but nothing yet has helped.

Scott

**Comment by moz4r** [comment]
Hi scott, maybe your jaw servo is not well calibrated : 
Can you check this : 
Move Jaw servo to 0 -> Jaw must close
Move jaw sevro to 180 -> jaw must open 
Is it inverted ?

**Comment by DSBRobotics** [comment]
It doesn’t move from 0-180 but it works well in older program. Same settings used. My issue is trying to delay movement to sync with audio. Using delay now only makes full movement, so he just opens mouth, like saying “duh”

**Comment by DSBRobotics** [comment]
To correct Jaw “input MAP” is 0-180... output MAP 37-85. Fully closed at 0, fully open at 180.

Scott

**Comment by moz4r** [comment]
Ok your calibration is good ! so I understood you want to sync jaw with audio, instead of software mouth control ?

**Comment by DSBRobotics** [comment]
There is a jaw tweak command that I was trying to use. I can go the audio route but was trying to keep it simple but maybe that’s really the simple way at this point

**Comment by DSBRobotics** [comment]
Still have issue syncing mouth movement with speech. Maybe it is how I’m trying to use it. Can someone please explain how “MouthControlJawTweak” works!! 
State to false , jaw moves well before speech. I make statement “true” and jaw just opens wide with speech but still not sync.

**Comment by supertick** [comment]
UI shows configurable values - user can adjust to his/her preference 
![image](https://user-images.githubusercontent.com/1266144/152696595-6cf064e4-8b10-4aa2-ae07-31768dd325e1.png)
