### ISSUE TITLE
Ivy download hangs on ras pi / poor network

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#174]
When installing services on a ras pi 3 , I noticed that I had to kill mrl and restart it 3 times with the "-install" option before it successfully installed all the services.  There was no initial ~/.ivy2 cache directory, so perhaps some of the downloads failed.  

we should consider some sort of retry logic and better logging to the end user so they know if things are stuck or progressing better.

**Comment by supertick** [comment]
feeback to the webgui is now asynchronous - so they will see the actual install logging stop
