### ISSUE TITLE
command line -i -install still borked

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#177]
it currently does not do anything (although the gui "install all" does)

**Comment by supertick** [comment]
worky for me ...

**Comment by kwatters** [comment]
On a RasPI,  I download the "latest", did a  "java -jar myrobotlab.jar -install"  .. that completed.
then I run the following command:

java -jar myrobotlab.jar -service runtime Runtime python Python gui SwingGui -invoke python execFile /home/pi/github/pyrobotlab/home/kwatters/Harry.py

The end result is that myrobotlab does not run the script, and oddly enough the SwingGui doesn't launch, it just stays at the agent cli.

**Comment by kwatters** [comment]
installing on the raspi seems to work and install everything properly now.  we can close this one.
