### ISSUE TITLE
Test Basic Start/Stop of all Services - and Serialization of all Services

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#18]
The initial testing harness and process are in:
Besides finding errors we have 2 new very useful services Agent & CLI
The test service has found the following problems:

The following appear to suffer from invalid dependency descriptions
OpenNI - SimpleOpenNIJNI - 
PlayerStage
SoccerGame
Solr
Wii

MRL typically follows the mantra - "MRL is not the GUI and the GUI is not MRL", another way to state this is MVC - where model data is part of the service.  If that is the case the model data should be serializable.  The following classes fail serialization. Two types of serialization are being tested .. binary and JSON - I believe if binary fails JSON is not tested

These are the very basics of testing - but now we have a system which can be enhanced and more meaningful tests can be conducted routinely.  Yay !

```
  "detail": "==== testing org.myrobotlab.service.GPS ====",
          "level": "error",
          "detail": "java.io.ByteArrayOutputStream ------\r\njava.io.NotSerializableException: 
 "detail": "==== testing org.myrobotlab.service.InMoov ===="
          "detail": "class org.myrobotlab.service.InMoov declares multiple JSON fields named lastError ------\r\njava.lang.IllegalArgumentException: class org.myrobotlab.service.InMoov declares multiple JSON fields named lastError\r\n\tat 
  "detail": "==== testing org.myrobotlab.service.InMoovGestureCreator ====",
          "detail": "class javax.swing.JComponent declares multiple JSON fields named accessibleContext ------\r\njava.lang.IllegalArgumentException:

      "detail": "serializeTest for org.myrobotlab.service.LeapMotion2",
          "detail": "com.leapmotion.leap.Controller ------\r\njava.io.NotSerializableException: com.leapmotion.leap.Controller

"detail": "==== testing org.myrobotlab.service.MQTT ====",
          "detail": "java.lang.Object ------\r\njava.io.NotSerializableException: java.lang.Object\
```

 "detail": "==== testing org.myrobotlab.service.RobotPlatform ====",
      "statuses": [
              "detail": "java.lang.Object ------\r\njava.io.NotSerializableException: java.lang.Object\r

```
      "detail": "serializeTest for org.myrobotlab.service.ServoOrchestrator",

          "detail": "org.myrobotlab.service.ServoOrchestrator$SettingsItemHolder ------\r\njava.io.NotSerializableException: 
```

**Comment by kwatters** [comment]
So, I think this might be covered partly by my serialization test ...   I agree, we should start/stop release / restart this unit test.  I can rename the serialization test to be something like AllServicesTest   .. that does basic operations on all services to ensure they start/stop/serialize/restart/getMetaData .. maybe some other methods..  
This should help with our code coverage reports also (hopefully)
