### ISSUE TITLE
We should publish a pom.xml file for each of the custom dependencies that exist in the mrl repo.  This will allow the .m2 cache to fully cache the dependencies locally for a build.

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#187]

**Comment by kwatters** [comment]
I've added placeholder pom files for all the dependencies that we use in the repo.  You might need to delete your local .m2 cache to see it take effect, but the net of it is this will fix the warning message about "no dependency information" for our custom jars.
