### ISSUE TITLE
Distributed Build System

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#188]
We need to figure out a way to have multiple systems build & test mrl and post all their results to a public place.

**Comment by kwatters** [comment]
I think this is probably done?  What else do you have in mind for this issue?

**Comment by supertick** [comment]
Ya I think it worky pretty well - http://build.myrobotlab.org:8888/ 
I'd like to get Travis to push its results there too - but I'll let that fall outside the scope of this ticket ..
I the progress side .. I took out the failing deployment of Travis .. and IT WORKY BUILD ON TRAVIS !!
https://travis-ci.org/MyRobotLab/myrobotlab
