### ISSUE TITLE
Backup Artifactory

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#189]
We need a backup or sync of the Artifactory service.  As this become more populated with specialized libraries, we would be in a very bad place if it suddenly "disappeared"

**Comment by kwatters** [comment]
Agreed.. what do you recommend?  I think perhaps a weekly snapshot of the Ami?  Perhaps a small cron job that kicks that off.  Just need to watch out for aws charges

**Comment by kwatters** [comment]
@supertick  let's take one snapshot of the AMI when we release nixie, so we know we can spin a new one if we need to that's consistent with the release...  It'll be better when we can have a more formal backup in the future or perhaps I could host an artifactory instance that could mirror...  just not sure how that would be setup.

**Comment by supertick** [comment]
I backed up artifactory and moved it here - https://drive.google.com/file/d/1HOqP0fwGzhQJB_tL6PS7J1oWtzp5NuZo/view?usp=sharing

Additionally, I did a aws snapshot.

I think think this should just be automated and scheduled, e.g. once a month.

This is progress, I'll drop it from Nixie but keep the ticket open. Perhaps in Ogre we can mirror or schedule it.

**Comment by supertick** [comment]
wow ... lots has changed .. its all docker and snapshots to s3
closing ...
