### ISSUE TITLE
Hide swing tabs if there is nothing inside

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#196]
as option, hide by default ?

**Comment by LunDev** [comment]
Sounds like a great idea,
but I wouldn't do it by default as it is the fastest/easiest (and for many beginners probably the only) way to tell if a service is actually running/has been started

**Comment by kwatters** [comment]
I think this would be confusing to users. If you launch a service, you should see it show up in the GUI.  If a service doesn't have a GUI, we should add one.

**Comment by moz4r** [comment]
yeh guys this would be confusing. lets put an option somewhere

**Comment by supertick** [comment]
Swing ?  what is that ?
