### ISSUE TITLE
Deep Learning, unable to load DL4J in OPENCV service, not responding

### ISSUE THREAD

**Issue by Roger200** [MyRobotLab/myrobotlab#198]
G'day Everyone and community, 

Below is how I replicated the issue, 

Version: myrobotlab.1.0.2693

I started MRL InMoov by double clicking on "start_InMoov.bat"

And then I copied and run the script in the python tab of MRL (http://myrobotlab.org/content/deeplearning4j-opencv-and-real-time-object-recognition  I used the python script here.)

And then MRL goes to non-responding mode..., 

And then I followed the comment below

http://myrobotlab.org/content/deep-learning-unable-load-dl4j-opencv-service-query#comment-10160

And then I hit Ctrl-C in the command window for mrl 'woke' it up and made it start responding again as per in the comment by  mimorikay. Then DL4J kicked in the OPENCV service and it works again. 

Thank you for your help, 
Kind Regards, 
Roger

**Comment by supertick** [comment]
fixed long ago - (manticore scripts not supported)
