### ISSUE TITLE
Ivy is not processing peer dependencies.

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#205]
In Arduino:
meta.addPeer("serial", "Serial", "serial device for this Arduino");

jssc is not being installed

**Comment by supertick** [comment]
Hmm .. installing Arduino, does install jssc which is in serial ...
What are you seeing moz4r ?

**Comment by supertick** [comment]
![jssc](https://user-images.githubusercontent.com/1266144/40697407-e899daf4-637e-11e8-93e6-dff2b38812dc.png)

**Comment by moz4r** [comment]
Hi ! hehe you put your finger on it : there is a screen that say it is installed BUT there is nothing inside libraries , look inside : 

![image](https://user-images.githubusercontent.com/18124594/40710746-c8bccf22-63f9-11e8-976d-fbf2f04650d0.png)

**Comment by supertick** [comment]
![homer-doh](https://user-images.githubusercontent.com/1266144/40722150-60cf1d1c-63d0-11e8-9706-17b53669499b.jpg)

**Comment by supertick** [comment]
Thanks ... working on it now

**Comment by supertick** [comment]
Fixed nixie 1.1.172
