### ISSUE TITLE
Get runtime serialized ( just a little )

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#206]
Runtime is not yet serialisable, I just need few of things serialized.

Will add an optional filter (field list) to copyShallowFrom Inside services  ( if it not a too bad idea ? )
So runtime still not serialisable, but only few fields .

**Comment by supertick** [comment]
it says this in the log because it's the "last" to be serialized ..
it is serialized - but is an empty object - I took out Runtime.repo and some other information (marking them as transient) - because i wanted to remove them

What parts are you interested in serializing moz4r ?

**Comment by moz4r** [comment]
pushed some desperate hack to serialize only one var ( for now, it is **String currentLanguage;**  ) inside runtime : 
https://github.com/MyRobotLab/myrobotlab/commit/39f740fda74b018b0c6c209874b41ce0706b198a#diff-d323334af8fdd3f7a62ba82be5816153R1730

Goal is to store the last overridden system language for next restart.
Cleaner thing is welcome :)

**Comment by supertick** [comment]
Ya .. your right .. it probably shouldn't be there ... 
Runtime is for 

- installing service dependencies
- creating and starting services
- destroying services
- maintaining the registry of services

so many things not related at all to Language

I'm beginning to understand what you want but for clarity can you do a mrl post which describes your story ?
Common to software development are "stories" where you describe how you want something to behave and in what context ..
For example 

I as an InMoov user want to write the following script..
i01 = runtime.start('i01', 'InMoov2')
i01.setLanguage('fr')
and after I shutdown, the next time it starts it will remember to speak French and recognize French

**Comment by supertick** [comment]
runtime is serializable - in the form of runtime.yml as potentially all services have this capability
