### ISSUE TITLE
Look into borging J4K  (Java 4 Kinect library)

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#211]
Info here:
https://research.dwi.ufl.edu/ufdw/j4k/

**Comment by hairygael** [comment]
Hey nice!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-06 17:14 GMT+02:00 Kevin Watters <notifications@github.com>:

**Comment by kwatters** [comment]
as far as i can tell, this library is windows only..   and unfortunately, it's also not published to maven central.   but we could host it in the mrl repo so we can integrate possibly.

**Comment by supertick** [comment]
there is lots of problems with this as a driver for kinect development
