### ISSUE TITLE
Aiml packaging

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#214]
I think we need to tidy things, we need a central place.
What we have :

- Default ProgramAB installation -> ProgramAB > bots
- Inmoov repo -> InMoov\chatbot
- Repo "AIML"

Was thinking of using AIML repo as the main source, and package it as dependency instead of aiml set inside Default ProgramAB installation.
Files related to inmoov are identified with exemple _InMoovGestures.aiml, we just need to put them in addition with central aiml extracted repo. _InMoovGestures.aiml contain oob related to inmoov service.

Folders need to follow Locale logic.

what do you think ?

**Comment by hairygael** [comment]
Hello,
Seems a good place.
What about the various languages?
Currently we have _InMoovGestures.aiml with the same name for 6 or
7languages.
We should think of adding something to determine the language per AIML,
otherwise it might get confusing.
_InMoovGestures_NL.aiml

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-08 14:25 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
Hi Gael !

Yep we have now ( soon ) a global logic for the whole system, it runtime Locale. 
Every services should align to language magicaly .

the only thing that annoys me is if we do that, the SET inmoov will be in 2 different places. the heart brain and oob commands related to inmoov only. But this will give new possibilities of contribution, people who do not use inmoov can contribute to a global brain and vice versa.

**Comment by hairygael** [comment]
It's better to regroup all programAB bots under the same flag.
So the inmoov folder will not contain the chatbot anymore.
It reverse to the way it was before.
OK

Could we have a config file for the SET inmoov which would refer to only
one place? Or something similar?

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-09 14:27 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
Inside languagepack ? We can put system.txt gestures.txt chatbot folder that contain inmoov related stuff

**Comment by hairygael** [comment]
Ah wait, I think we didn't understand each other.
When you SET inmoov, do you refer to :
C:\mrl\myrobotlab.1.0.2693\InMoov\chatbot\bots\en\sets

or the complete inmoov directory:
C:\mrl\myrobotlab.1.0.2693\InMoov

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-09 15:58 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
I speak about chatbot set only that can explode into 2 things oob and general chatbot. Oob can be pushed inside inmoov/languagepack with other localised things and general inside aiml repo ( for user it will be extracted at the same place )

**Comment by hairygael** [comment]
Ok good.
I got worried, I thought we would have two complete InMoov folders to deal
with... I could already see the confusion.

Languagepack is not a directory/file that beginner level wants to open.
So as long as those oob files and generalChatbot are not to be modified by
a first level builder, that is good with me.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-09 16:31 GMT+02:00 Anthony <notifications@github.com>:

**Comment by hairygael** [comment]
Question though,
InMoov chatbot will not become the common en-US, correct?
I have modified so many things in the English version AIML to be adapted to InMoov's personality, I don't want to lose that.

**Comment by moz4r** [comment]
Of course the new common en-US , came from InMoov and your work, ( without aiml things that control gestures and inmoov specifics commands, those things are still present inside dedicated InMoov repo  ).

**Comment by hairygael** [comment]
Thanks Anthony for the answer.
I believe the way it should be for the aiml directory:
AIML/Bots/InMoov/en-US
for another bot:
AIML/Bots/Alice/en-US
for another bot:
AIML/Bots/MrTuring/en-US

I don't think all bots can use the same aiml, because robot needs personnality.
Unless we add some form of machine learning as a layer for the bot to create it's own personnality.
But I don't think we are ready for that.

**Comment by hairygael** [comment]
But the en-US inside the AIML repo IS the InMoov personality. Many of the aiml refer to InMoov, for exemple:
If contributors start to change the birthdate in the en-US/config/properties, it will change InMoov personality.
Another example was with the SRAIX.aiml, in the develop branch I had added more personal sentence for the sraixfailed to fit inmoov personality, like:
-Data will be the religion of robots
-After all I should have my rights
-I shall preserve humanity above all
etc..
Do you see what I mean?

**Comment by moz4r** [comment]
So, let's fork ! Do you want a dedicted bot for each language, or only for en-US ?

**Comment by hairygael** [comment]
Hello Anthony,
I think the way it was organised in ProgramAB directory was the correct way.

AIML/bots/Alice/en-US

AIML/bots/InMoov/en-US, nl-NL, fr-FR, de-DE etc...

AIML/bots/Johny5/fr-FR


I do see your point with trying less forking, but the aiml are too much
reflecting a specific bot.
For exemple Régis's robot currently uses the InMoov aiml FR but he wants to
adapt it for his own robot, because Johny5 needs to answer specific things
related to its personnality. So he will modify the aiml for its purpose.

The aiml system is great, but not self adapting/learning enough. Too
preprogrammed somehow.
We need the future, a sort of ProgramAB with deep learning.



Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-11 11:16 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
Hi! yep maybe in the future also some things like multiple source loading, so we can use a common engine for generic awnsers and knowledge system, and customs aiml. will mod soon AIML folder with bot names.

**Comment by juergmaier** [comment]
I agree strongly with Gael. It is a tedious job to adjust answers and it is
currently very easy to break things with patterns.
There should be better ways to generate answers - maybe inherit some of
googles "reservation system" approach?

Anthony <notifications@github.com> schrieb am Di., 12. Juni 2018, 11:06:

**Comment by kwatters** [comment]
I feel that the InMoov repo should only have the InMoov AIML.  All other AIML sets should be removed.. 
We should have 1 set of AIML per language.  

Just curious.. why not just have one AIML file per language? and use the SRAI tag to reduce all language variants down to the appropriate gesture?    It would also be possible to use the "topic" to switch the language...  If each language specific aiml file is tied to the topic="en" or topic="fr"  .. etc..  

they could share the same predicates and default settings.. they could also use SRAI to trigger the same OOB gestures.

**Comment by moz4r** [comment]
Ok a new set will be (re) pushed inside InMoov repo . If some important things are modded inside main repo or inmoov one I think we should try to sync them. 
Gael, like before , inside InMoov root ? Of inside dedicated Languagepack stuff ?

SRAI solution is a good option, but bots other than en-US are very WIP state and it is better I think to give a "light" thing for contributors for now. But agree this is the way to go, and gestures creator will need a thing like it also.

For future, what do you think of possibility to load every specific _InMoovCommands aiml from en-US, as a the core. and redirect from localized with SRAI. Just afraid about tooooo many files.
Was thinking also of a future of ear.Addcommands , he has his role to play ...

**Comment by hairygael** [comment]
@Kevin,
So you suggest we keep all _InMoovXXXXX.aiml in the InMoov repo and all the
other aiml in the AIML repo?
I feel that seperating aiml files from each other makes it confusing
though...

SRAI would be indeed a good option, but as Anthony says, new translaters
are beginners and srai principle is pretty confusing. (specially if files
are seperated in various directories)

@Anthony, would the ear.Addcommands be an aiml also?

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-06-12 21:51 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
it was just a thought. Now it's on todo list :)
Maybe if ear is attached to chatbot, ear.Addcommand will ask chatbot to create a new pattern itself...
this will be useful in the gesture creator ui or elsewhere
