### ISSUE TITLE
Service json saved to .myrobotlab/{ServiceType}.{name}.json

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#234]
This prevents different service types being substituted into the same solution with the same name from conflicting with internal state and details.

e.g. if we have a system where we want to switch speech synthesizers from NaturalSpeech to MarySpeech - and our system uses the service name "speech" there will be problems in loading and saving the json

**Comment by moz4r** [comment]
great solution

**Comment by supertick** [comment]
fixed
https://github.com/MyRobotLab/myrobotlab/commit/3d1bb1756f516bb0f4006b4157d7d9f4cd5836a4
