### ISSUE TITLE
CmdLine converted to Apache Cli

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#237]

**Comment by supertick** [comment]
By popular demand :)

**Comment by kwatters** [comment]
We'll go with commons-cli version 1.4.  This will become a dependency for the "Agent"  I guess? also for "Runtime" ? seems like command line parsing should be in one place or the other.. but we've got it in 2 places...    It'd be nice if there was only 1 command line to worry about...

**Comment by supertick** [comment]
agent completely removed - all cmd line options are done in a single process - batch/shell scripts can start with appropriate jvm parameters desired
