### ISSUE TITLE
No Point using LK FILTER on OpenCV mac

### ISSUE THREAD

**Issue by Alessandruino** [MyRobotLab/myrobotlab#24]
If I click on a point of the display,  using LKOpticalTrack I can t see the point being set and tracked...

**Comment by supertick** [comment]
This was not just isolated to mac - but had to do with the 2.4.10 update on OpenCV .. A considerable amount of changes occurred with the updated JavaCV including how to access native arrays and pointers.  There are still issues with some of the filters (notably - GoodFeatures) - These will need to be fixed one by one ..   Unit tests will need to be created too - I am currently working on a TrackingTest which should verify the LKOptical is working properly each build
