### ISSUE TITLE
modifications to improve quality

### ISSUE THREAD

**Issue by scanlight** [MyRobotLab/myrobotlab#252]
hi all.
i have been playing with MRL for a while now and some things start be to annoying.
maybe this can be changed in the next releases.

when using internet to find an answer, it always ends with "answers dot com" somehow this must be cut off automatically.  this would make it a lot more realistic instead of reading a web page.

remove the "contacts" option. 
very often the PC didn't understand me. and asks if i want to search for a contact named .... even when i say "no" its reading a full script/adress line.

expand the AIML response library.
very often inmoov doesn't find a good response to a question. and returns some basic responses "people say am smart and ......" " am loyal..."   
maybe this can be somewhat improved to make it an experience to talk/chat with the inmoov

for the rest keep up to good work. am loving it!

With kind regards
robbert lievens

**Comment by supertick** [comment]
sraix uses new search services - they are worky
