### ISSUE TITLE
Ipcamera does not work.

### ISSUE THREAD

**Issue by wilcovantoorn** [MyRobotLab/myrobotlab#253]
When launchin opencv and want to start ipcamera, it gives an error regarding framegrabber not found. I can open the stream in my chrome tab but when i enter the url in the box and press capture it gives the error class not found framegrabber. Send a noworky to give details.

Starting ffmpeg is no problem with the ipcamera i use.

**Comment by supertick** [comment]
OpenCV had lots of refactor in Nixie ...
If you could - please test now - IPFrame grabber should be supported  (latest Nixie version) 

![ipcamera](https://user-images.githubusercontent.com/1266144/52061538-7026e580-2566-11e9-8d85-ec67b69c39e9.png)
