### ISSUE TITLE
Format chatbot UI

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#258]
just to make things a little clearer and tidy

![image](https://user-images.githubusercontent.com/18124594/45417138-c495fb00-b681-11e8-98e8-72ce761fe093.png)

**Comment by supertick** [comment]
I think it should follow a regular chatbox format ...
e.g.
**Anthony** :  Hello bot
**en-US** : Hello Anthony, its great seeing you.
**Anthony** : What is going on ?
**en-US** :  The weather is 30 degrees Celsius and slight winds from the northeast.

**Comment by LunDev** [comment]
either that or the aligned version: e.g. align the bot's message to the left and the user's to the right
@supertick 's version is easier to implement, so I vote for that one :p

**Comment by moz4r** [comment]
great ! we are agree the screenshot is what we have today

**Comment by moz4r** [comment]
more sexy, progress

![image](https://user-images.githubusercontent.com/18124594/45636361-c7d91e80-baa7-11e8-8907-688ac73771d9.png)

**Comment by hairygael** [comment]
I agree as well, Grog's version is tidy.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>
