### ISSUE TITLE
HttpClient versions - stop the madness

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#263]
Currently Runtime meta data is defined as :

meta.addDependency("org.apache.httpcomponents", "httpclient", "4.5.2");

ProgramAB is
    meta.addDependency("org.apache.httpcomponents", "httpclient", "4.5.2");
    meta.addDependency("org.apache.httpcomponents", "httpcore", "4.4.6");

If httpclient is critical to the very core of mrl - then perhaps all version references should be removed - and the Runtime get a "full" description

    meta.addDependency("org.apache.httpcomponents", "httpclient", "4.5.2");
    meta.addDependency("org.apache.httpcomponents", "httpcore", "4.4.6");

Anyone disagree ?

**Comment by wilcovantoorn** [comment]
It Would be the most logical approach.

Op za 15 sep. 2018 om 17:01 schreef GroG <notifications@github.com>:

**Comment by kwatters** [comment]
who ever gets around to it, http client/core should be excluded from all services and included in either runtime or in httpclient.  (my preference would be runtime.. for simplicity)
