### ISSUE TITLE
Serialisation issues

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#283]
There is no more ( almost ) json writeOut and writeIn
manual runtime.saveAll() / loadAll() seem worky

**Comment by supertick** [comment]
When should it write out ?
![serialize](https://user-images.githubusercontent.com/1266144/46644237-4e779d80-cb34-11e8-855c-940c3353eb20.png)

**Comment by moz4r** [comment]
If I remember, it was worky when we use the [service].save() , and also at runtime.shutDown()

**Comment by supertick** [comment]
Fixed in - https://github.com/MyRobotLab/myrobotlab/pull/334
