### ISSUE TITLE
OpenCv UI issues

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#284]
Just found one, on the default screen we see after service started, videoinput selected, after clicked to capture, no "stop capture" button

**Comment by kwatters** [comment]
yup. i'm pretty sure grog fixed this.. i also had the same fix on the lloyd2 branch.

**Comment by hairygael** [comment]
When launching:
 **opencv.capture()** or **opencv.stopCapture()**
It automaticaly resize the SwinGui to a disproportianal size regarding the screen.

**Comment by moz4r** [comment]
reproduced, oh also opencv.setFrameGrabberType() do not broadcastState(), so a different framegrabber is showed inside UI

**Comment by supertick** [comment]
should all be fixed ... 
capturing is a lot more code friendly ..
cv.capture("someFile.mp4") 
cv.capture("http://somewebpicture.jpg") 
cv.capture("https://www.youtube.com/watch?v=SLp5YVplJAQ") 

looked for cached or recorded files in the OpenCV directory
