### ISSUE TITLE
NaturalReaderSpeech out of work Nixie 283

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#298]
Seems something is broken with the version stated in the title. 
Instead of loading NaturalReaderSpeech voices, it loads the LocalSpeech voices.

**Comment by supertick** [comment]
Hi Gael,
How do I reproduce the problem ?  I've used NaturalReaderSpeech with InMoov and it appeared worky ...

**Comment by hairygael** [comment]
Hello Greg,
Before launching the START_INMOOV.bat
Open the inmoov config directory,
Select and open:
*service_5_Mouth.config*
Set it as:

*Speechengine=NaturalReaderSpeechVoiceName=US-English_James*
or
* VoiceName=US-English_Matthew *

On my test it doesn't speak with NaturalReaderSpeech but with LocalSpeech
voice.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>

**Comment by moz4r** [comment]
Not related to LocalSpeech, but of a new NaturalReaderSpeech voice map list. 
So you get always the same voice ( default ).

You can check / test voices Inside mouth Gui , or print mouth.getVoices()


Aditi female en
Amy female en
Astrid female sv
Audrey female en_GB
Brian male en
Carla female it
Carmen female ro
Celine female fr
Chantal female fr
Conchita female es
Cristiano male pt
Dora female is
Emma female en
Enrique male es
Ewa female pl
Filiz male tr
Geraint male cy
Giorgio male it
Gwyneth female cy
Hans male de
Ines female pt
Ivy female en
Jacek male pl
Jan female pl
Joanna female en
Joey male en
Justin female en
Karl male is
Kendra female en
Kimberly female en
Liv female no
Lotte female nl
Mads male da
Maja female pl
Marlene female de
Mathieu male fr
Matthew male en
Maxim male ru
Miguel male es
Mizuki female jp
Naja female da
Nicole female en
Penelope female es
Raveena female en
Ricardo male pt
Ruben male nl
Russell male en
Salli female en
Seoyeon female ko
Takumi male jp
Tatyana female ru
Vicki female de
Vitoria female pt

**Comment by hairygael** [comment]
Very nice the new mouthGui!
I see now the new list.
How would I configure the voice in the InMoov_ config files to be automaticaly launched?
VoiceName=Matthew male en
Doesn't seem to work, I get the french default Mathieu male fr

One more question, shouldn't the mouthGui also display the speechEngine?

**Comment by moz4r** [comment]
You can try just "Matthew" , good idea we can add the engine name for information, and status also.
In future we will not need anymore service_5_Mouth.config .

**Comment by hairygael** [comment]
The webgui would look fantastic if it would look like what Sebastien has done graphicaly with the Mqtt tests

**Comment by supertick** [comment]
![error](https://user-images.githubusercontent.com/1266144/46743881-d8bc2080-cc5e-11e8-9a79-f1998619f9b6.png)

fixed - for "all" speech synthesis services

**Comment by supertick** [comment]
![speech](https://user-images.githubusercontent.com/1266144/46744638-651b1300-cc60-11e8-8d4b-0eb64f1c51b7.png)
Additionally, if runtime or the computer has a language already set, the first "default" of a speech synthesis should be the first match of a valid language voice (if it exists)

**Comment by supertick** [comment]
closing

**Comment by hairygael** [comment]
Unfortunately NaturalReaderSpeech is broken again.
mp3 files are 0 bytes.
Seems NaturalReader changed again something on their website.

**Comment by supertick** [comment]
NaturalReaderSpeech is no longer supported
