### ISSUE TITLE
Vocal commands showed in chatbot window

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#305]
Version 1.1.294 Nixie test.
It would be handy when speaking vocaly via ear WebKitSpeechRecognition to the robot, that it would show text sentences in the chatbot window.

Currently when speaking to the robot, what I say or what the robot answers is not showed in the chatbot window, unless I manually type my text.

**Comment by moz4r** [comment]
Hi Gael, inside 294, vocal commands should appear inside UI, can you double check ?

![image](https://user-images.githubusercontent.com/18124594/46667970-6e0dd500-cbcb-11e8-8d2c-8d85d5504eae.png)

**Comment by hairygael** [comment]
Yes they show in the WebUI like it was in Manticore.
But don't you think it should also show in the chatbot window as converstion flows?

**Comment by hairygael** [comment]
Mmmh, not in my case with this exemple:
![brokenaiml2](https://user-images.githubusercontent.com/8484551/46669385-8f70c000-cbcf-11e8-86e5-6ff1afea6323.png)

**Comment by moz4r** [comment]
oh more clear ! what you are talking about is vocal commands. Not related to chatbot.
The chatbot said nothing, but sent an oob command to produce a mouth event "I'm fine thank you".

We can interface mouth events here, but I think it is not clean... 
Will propose something for you, also this will help to globalise gestures.

**Comment by hairygael** [comment]
Ho do you see the AIML correspondance now in Nixie?
The cmd.exe window doesn't show anything anymore, which was handy for to solve AIML issues.
![cmdwindow](https://user-images.githubusercontent.com/8484551/46670414-6d2c7180-cbd2-11e8-9436-e99d5065cc1d.png)

**Comment by moz4r** [comment]
updated howdoyoudo() as sample, so chatbot will do the job instead of mouth

**Comment by hairygael** [comment]
Great!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>
