### ISSUE TITLE
Breaking AIML in fr-FR

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#307]
Version 1.1.294 Nixie
Playing with the swingui I tried to switch from complete en-US to "ear fr-FR", "mouth Celine female fr-FR", "bot fr-FR". It worked!
But now whenever I try to do the same, robot says systematicaly "I have no answer for that".

In Manticore, I used to look in the cmd.exe window to find a hint why the AIML was leading to such answer, but in Nixie, the cmd.exe window doesn't display those informations anymore.
How do you guys look for those info now?
![brokenaiml1](https://user-images.githubusercontent.com/8484551/46668340-63077480-cbcc-11e8-8773-3b9e706fd472.png)

**Comment by moz4r** [comment]
also maybe we need to sort buttons

**Comment by moz4r** [comment]
I just reproduced this bug ( "I have no answer for that" ) by chance ... fixed > if topic is null, it break spacetime.
