### ISSUE TITLE
info level logging

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#308]
info level logging is too much verbose.
myself I tend to use a lot info for events. 
Today we are drowned in the news. A little bit of sorting to debug?

**Comment by supertick** [comment]
Sure ...  sounds good.

**Comment by moz4r** [comment]
![image](https://user-images.githubusercontent.com/18124594/46674323-1deb3e80-cbdc-11e8-85ca-1c798c3860e3.png)

**Comment by supertick** [comment]
merged !
