### ISSUE TITLE
RemoteAdapter service fail serialization of Runtime

### ISSUE THREAD

**Issue by MatsMRL** [MyRobotLab/myrobotlab#330]
RemoteAdapter service fail serialization of Runtime

To reproduce:
Start on MRL instance
Start RemoteAdapter
Press Listen
Start a second MRL instance
Start RemoteAdapter
Press Connect
Connect using: tcp://localhost:6767

Error message:
19:48:24.981 [HostA] INFO  class org.myrobotlab.service.Runtime - releasing url mrl://HostA/tcp://127.0.0.1:49498
19:48:25.095 [HostA:tcp://127.0.0.1:49498] ERROR class org.myrobotlab.logging.Logging - ------
java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.myrobotlab.framework.repo.IvyWrapper

**Desktop (please complete the following information):**
 - Ubuntu 16.04
 - Develop branch ( 20181029 )

I know some member(s) should be marked Transient, but I can't find what member it is.

**Comment by kwatters** [comment]
Is there any more to the stacktrace ?  did you happen to send a no-worky?    
There is a "ServiceSmokeTest" that does some testing of serialization.  There's a list of known offenders in that list.  I suspect we'll have to fix all of those before we can get RemoteAdapter working.

https://github.com/MyRobotLab/myrobotlab/blob/develop/src/test/java/org/myrobotlab/service/ServiceSmokeTest.java#L30

**Comment by supertick** [comment]
![remote](https://user-images.githubusercontent.com/1266144/47926170-26523480-de7d-11e8-8644-5d35fe11e994.png)
fixed in pr
