### ISSUE TITLE
Wrong behavior

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#331]
**Describe the bug**
During install of components via runtime, the pop up window says immediately "finished" and "exit", although it still is installing components.

**To Reproduce**
1. start mrl with a fresh install (1.1.955)
2. in runtime select to install inmoov component
3. see the install pop up window doing the strange behavior

**Expected behavior**
window should proceed the install, and propse to exit only when finished

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser chrome
 - Version 1.1.955

**Comment by supertick** [comment]
I've see the same thing.  I believe it happens when multiple installs get fired off at "near" the same time.  One will finish without errors, yet another in the background is still installing.  I fixed this by making the installs synchronized (submitted pr)

**Comment by supertick** [comment]
fixed in pr
