### ISSUE TITLE
Starting a new service after to instances of MRL have connected thru RemoteAdapter cause an infinite loop

### ISSUE THREAD

**Issue by MatsMRL** [MyRobotLab/myrobotlab#338]
**Describe the bug**
If you start two MRL instances and connect them using RemoteAdapter, starting a new service will cause an infinite loop. 

**To Reproduce**
1. Start an MRL instance. Start a RemoteAdapter. Set the RemoteAdpater to Listen
2. Start a second MRL instance. Start a RemoteAdapter. Set the RemoteAdapter to connect to the first MRL instance connect("tcp:/host1:6767")
3. Start a new service in one of the MRL instances.
4. An infinite loop of services will popup, making it impossible to send a "No worky".

**Expected behavior**
I expected the new service to be started in the local MRL instance and be visible in the remote MRL instance.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Not OS depenant. Reproducable in all. 
 - Version: Latest release ( 20181107 ) #960

**Comment by supertick** [comment]
very close - service doesn't exist anymore.  Remote connections are handled by WebGui and websockets
