### ISSUE TITLE
Virtual InMoov returns an error

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#342]
**Describe the bug**
Virtual InMoov returns an error after starting, the widow pops up and disappears living the error notice.

**To Reproduce**
1. Launch the START_INMOOV.bat in "Virtual" mode
2. See all the tabs getting initialized
3. When it comes to initializing Virtual InMoov
4. See the error notice

**Expected behavior**
Virtual InMoov window should be launched and stable

**Desktop (please complete the following information):**
 - OS: [windows10 pro]
 - Browser chrome]
 - Version [1.1.961]

**Comment by supertick** [comment]
simulator works - virtual mode is not a requirement to run simulator
