### ISSUE TITLE
organize the myrobotlab directory structure

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#365]
When services install their dependencies/resources we would like them to have a consistent layout for the files.

Resources installed per service should be installed into a directory like

<mrl_install>/resources/ServiceType

Data that is generated by an instance of a service running should be stored in 

<mrl_install>/data/ServiceType/ServiceName

The service name sub directory can be optional in the case of data that is shared across all instances of a particular ServiceType.  (Example.  OpenCV cache.)

Log files generated from mrl running should be moved into the 

<mrl_install>/logs/  directory

finally, the .gitignore file should be cleaned up to include just 
data, resources, and logs

**Comment by moz4r** [comment]
I like it, also this will cleanUp root folder.. nice, clean !
Compress logrotate at shutdown, maybe a good idea

**Comment by supertick** [comment]
this was implemented
