### ISSUE TITLE
Cannot shutdown camera device

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#386]
**Describe the bug**

stopCapture() ( using opencvFrameGrabber ) can't shutdown the device, the light of my webcam is still ON. ( OFF after runtime shutdown )

**To Reproduce**
```
cv = Runtime.start("i01.opencv", "OpenCV")
cv.capture(0);
cv.stopCapture(); // opencv is now not capturing but webcam hardware is still in use
```

**Desktop (please complete the following information):**
 - OS: win64

**Comment by supertick** [comment]
MRL does not control this.
Its between the OS &  javacpp & the camera driver ... I have seen things go bad before this way after a javacv update.  

BTW - doing the exact same script on a my windows laptop momentarily turns on the camera, then turns it off
