### ISSUE TITLE
enable / disable filter UI

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#393]
**Is your feature request related to a problem? Please describe.**
Possibility to enable / disable filter from UI

**Describe the solution you'd like**
a button / right click option ?

**Comment by supertick** [comment]
looks like kwatters added this - "double click" 
(green is enable) - white is disabled

**Comment by hairygael** [comment]
Very handy for gui users.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>
