### ISSUE TITLE
Capture Gesture should not get error if some parts are not activated

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#404]
**Is your feature request related to a problem? Please describe.**
It seems that when capturing a gesture, if one part of InMoov (here topStorm) config is not set as True it causes an error.
i01.moveHead(78.0,73.0,45.0,89.0,95.0,90.0)
i01.moveArm("left",66.0,58.0,85.0,82.0)
i01.moveHand("left",0.0,0.0,0.0,0.0,90.0)
i01.moveArm("right",133.0,79.0,110.0,95.0)
i01.moveHand("right",0.0,0.0,0.0,0.0,90.0)
------Traceback (most recent call last):  File string, line 1, in module  File C:/mrl/myrobotlab.1.0.2693.7/InMoov/gestures\captureGesture.py, line 13, in captureGesture    print i01.moveTorso(+str(i01.torso.topStom.getPos())+,+str(i01.torso.midStom.getPos())+,+str(i01.torso.lowStom.getPos())+)AttributeError: NoneType object has no attribute topStom	at org.python.core.Py.AttributeError(Py.java:205)	at org.python.core.PyObject.noAttributeError(PyObject.java:1013)	at org.python.core.PyObject.__getattr__(PyObject.java:1008)	at org.python.pycode._pyx140.captureGesture$1(C:/mrl/myrobotlab.1.0.2693.7/InMoov/gestures\captureGesture.py:13)	at org.python.pycode._pyx140.call_function(C:/mrl/myrobotlab.1.0.2693.7/InMoov/gestures\captureGesture.py)	at org.python.core.PyTableCode.call(PyTableCode.java:167)	at org.python.core.PyBaseCode.call(PyBaseCode.java:124)	at org.python.core.PyFunction.__call__(PyFunction.java:403)	at org.python.pycode._pyx301.f$0(string:1)	at org.python.pycode._pyx301.call_function(string)	at org.python.core.PyTableCode.call(PyTableCode.java:167)	at org.python.core.PyCode.call(PyCode.java:18)	at org.python.core.Py.runCode(Py.java:1386)	at org.python.core.Py.exec(Py.java:1430)	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:267)	at org.myrobotlab.service.Python$PIThread.run(Python.java:160)------

**Describe the solution you'd like**
It seems it would be logic that if you are working with only some parts of InMoov that you should be able to capture the gesture of only those parts anyway without getting an error. 

**Describe alternatives you've considered**
Or maybe get a warning message with explanation detail.

**Comment by hairygael** [comment]
Hello Anthony,
I will test to see if Nixie gets it worky.
Indeed this was done reported on Manticore.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>

**Comment by supertick** [comment]
closing
