### ISSUE TITLE
Test leap motion and inmoov hand tracking in Nixie

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#422]
Fahad Ali reported that starting leap tracking on the inmoov hand causes MRL to crash.  This issue is to test , that and ensure there's a working example script for it.

**Comment by supertick** [comment]
It crashes on Linux because the LeapMotion is a complete Jenga for java support "as bad as kinect" 
Apparently, it still works on Windows.  The correct fix is to use a less fragile network binding using websockets which I have started with LeapMotion2 but will not be completed in Nixie
