### ISSUE TITLE
Ear is borked

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#450]
Version 1.1.126 when running START_INMOOV.bat
Ear is borked in Swingui and in Google Chrome webkitrecognition. (webgui)
![earborked](https://user-images.githubusercontent.com/8484551/54047433-52891380-41d7-11e9-8adc-04d9cedff65b.png)

**Comment by hairygael** [comment]
tested version 1.1.127 it's a little better.
Chrome mic appears red for a moment but doesn't hear when speaking in the microphone.
Also i01.ear tab shows no user interface, when it should show some buttons and options.
![earborked2](https://user-images.githubusercontent.com/8484551/54070235-c2da7800-425d-11e9-8d50-e47ea91c7170.png)

**Comment by hairygael** [comment]
tested version 1.1.129 it's better.
Chrome mic appears and speaking in the microphone works, words are recognized. Robot responds.
i01.ear tab shows no user interface, when it should show some buttons and options.

**Comment by supertick** [comment]
fixed long ago
