### ISSUE TITLE
face recognizer filter overheat cpu

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#453]
Hello,
version 1.1.129
Face recognizer gets the cpu to rise in high temperature in a few seconds.
I didn't try on other PC, but I suspect it will be the same.
Currently using a Windows 10, i7-7700 CPU 3.6ghz, graphic card Nvidia 1070

Annoying drawback, the swingui over extends agin when lauching face recognizer filter.

**Comment by supertick** [comment]
opencv libs have been updated many times since this bug was entered
