### ISSUE TITLE
START_INMOOV.bat can't find myrobotlab.jar

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#457]
Hello,
Testing version 1.1.133
When launching the START_INMOOV.bat file, the prompt throws the error: 
Error: Unable to access jarfile myrobotlab.jar
And then it closes the prompt command.

My tree directory is like this (since ages):
C:/Documents/myrobotlab/myrobotlab.1.1.133/myrobotlab.jar

**Comment by supertick** [comment]
Maybe it was a bad download ?
I don't get this - when I install latest 133 in new directory .. do install ... START_INMOOV.bat gives me this ...

![gael](https://user-images.githubusercontent.com/1266144/54490612-88cc3000-4874-11e9-9c50-806c913fc151.png)

**Comment by hairygael** [comment]
Ah mmhh...
Ok I will try to re download and re install and let you know.
:)

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>

**Comment by hairygael** [comment]
New download, new install, it's worky!
We can close this ticket.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>
