### ISSUE TITLE
setAutoDisable seems borked

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#478]
Testing version 1.1.150 with InMoov-develop
When launching the START_INMOOV.bat all servo are supposed to be setAutoDisable as True,
but it doesn't happen.
Looking on swingui the buttons of all servo are set to setAutoDisable : false
It appears you can't manually click to change to "true" either in the swingui.

**Comment by supertick** [comment]
Hi Gael,
As a warning servo.moveToBlocking is now (temporarily) bork'd too.   
Servo is getting new capabilities to handle any type of encoder (digital, analog, & kwatters' amt models)
You might want to hold off testing until we get this updated.
Thanks.

**Comment by supertick** [comment]
Fixing these things now ....

**Comment by hairygael** [comment]
Ok cool

**Comment by supertick** [comment]
fixed long ago i believe
