### ISSUE TITLE
Build must not 'deploy' jar if it fails test

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#54]
Currently "all artifacts" are copied to s3 on a successful build.  They should not be if tests fail - this needs to be handled "in the build script" and not in Jenkins nor on Travis.

Spreading config over multiple systems to manage becomes a pain in the arse..

**Comment by supertick** [comment]
verified - Travis does not upload failed artifacts

**Comment by supertick** [comment]
Additionally, it needs to send the test/report artifacts EVERY BUILD - including failed tests

**Comment by supertick** [comment]
not worky as needed

**Comment by kwatters** [comment]
now that we're using jenkins, we should probably just close this.

**Comment by supertick** [comment]
Ya it's worky yay Jenkins!
