### ISSUE TITLE
ApiMessages and ApiMessages2 attempt to decode params after already decoding Message, ClassCastException thrown

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [MyRobotLab/myrobotlab#545]
Message is decoded from json using CodecUtils in process(). This is apparently recursive, and params are subsequently decoded in msg.data (no longer an array of Strings, but an array of the actual data)

https://github.com/MyRobotLab/myrobotlab/blob/0ba09dc6a8695ef98ec86189d6b37998a9a6cf3d/src/main/java/org/myrobotlab/codec/ApiMessages2.java#L34

Then, ApiMessages2 (and ApiMessages, in a more roundabout way) attempts to decode params again using MethodCache.getDecodedJsonParameters(), which accepts an array of objects but casts each element to a String

https://github.com/MyRobotLab/myrobotlab/blob/0ba09dc6a8695ef98ec86189d6b37998a9a6cf3d/src/main/java/org/myrobotlab/codec/ApiMessages2.java#L44
https://github.com/MyRobotLab/myrobotlab/blob/0ba09dc6a8695ef98ec86189d6b37998a9a6cf3d/src/main/java/org/myrobotlab/framework/MethodCache.java#L615

The result is if the message does not contain data that happens to be a string in the first place, a ClassCastException is thrown.

This is only present in api_refactor branch, develop branch has it correct. Unless I'm completely misreading this, which is certainly possible

**Comment by supertick** [comment]
Ya ... its all fixed locally,  I got several more pushes to do ..
The "interesting" take-away I've learned is strongly typed languages (like Java) require double encoded messages (encode parameter then encode msg container) while type-less languages (Python Javascript) require only a single encoding.
For uniformity most likely double encoding will be the standard - need to verify this still ...

**Comment by supertick** [comment]
Use the new method cache - it is a replacement for all decoders - it has its own "correct" decoding
(org.myrobotlab.framework.MethodCache)
