### ISSUE TITLE
Example InMoov script error with 1.1.5

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#551]
The available example python scripts for InMoov in the python tab are doing a strange thing when testing them with Nixie 1.1.5.
The voice repeats many times "not yet translated" and cause MRL to freeze.
You can try with this one to see on your own:
https://github.com/MyRobotLab/pyrobotlab/blob/develop/service/InMoovHand.py

**Comment by supertick** [comment]
scripts need refactoring - nixie should not require scripts to start
