### ISSUE TITLE
Ensure that all services extract all of their resources into their own resource directory.

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#617]
When a service is installed it will download it's resources (java dependencies and often a zip file containing other dependencies.)

It would be nice if a service could extract all of it's resources into it's own directory (or set of directories)
This way, an upgrade of a service would be as simple as deleting (or backing up) a single resource directory and unzipping/installing the new version .

**Comment by supertick** [comment]
This is how all independent services currently work
