### ISSUE TITLE
http://localhost:8888/#/service/i01.ear

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#62]
I don't seem to be the only one having this issue, Markus had the same today.
http://localhost:8888/#/service/i01.ear doesn't launch the microphone on Google Chrome when using version 1.0.2132. The webgui is correctly launched though.
We do not launch the whole webgui but only the ear.
This is happening when launching the inmoov repo with START_INMOOV_BAT and also when using the minimalHand.py.
For info, it was worky with version 1.0.2122

**Comment by moz4r** [comment]
tested last build  with this little fix on repo script+minimal script, ok for me
better for you ?

**Comment by kwatters** [comment]
It's important to make sure you launch the browser after the i01.ear service has been started.  Otherwise, you'll get a blank browser page.

**Comment by hairygael** [comment]
Thanks for this important info, I modified the minimalHand script on the
InMoov repo.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-03 15:27 GMT+02:00 Kevin Watters <notifications@github.com>:

**Comment by supertick** [comment]
Has this been verified worky ?
Can it be closed ?

**Comment by hairygael** [comment]
yes worky!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-04 3:18 GMT+02:00 GroG <notifications@github.com>:
