### ISSUE TITLE
Create MarySpeech GUI similar to its online webdemo - to switch voice and effects

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#67]

**Comment by hairygael** [comment]
Hey very nice!!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-05-27 22:25 GMT+02:00 Anthony <notifications@github.com>:

**Comment by johnharland** [comment]
I tried it in 1.1.6 and it is vey neat. Will be easier to pick a good voice!

**Comment by hairygael** [comment]
Quick thought:
Is the volume adjusting the system volume?
If no, it is better to set by default to max.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-05-28 19:21 GMT+02:00 johnharland <notifications@github.com>:

**Comment by moz4r** [comment]
The volume adjust only audiofile utterance related, so it is hardware universal. by default it is full power

![image](https://user-images.githubusercontent.com/18124594/40626522-69b34858-62b9-11e8-876c-6ba8539d31f9.png)

**Comment by hairygael** [comment]
Great!

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2018-05-28 20:55 GMT+02:00 Anthony <notifications@github.com>:
