### ISSUE TITLE
python open file dialog

### ISSUE THREAD

**Issue by juergmaier** [MyRobotLab/myrobotlab#68]
w10/64, v 2141
using the open file dialog and acting on one of the shown files not with open but e.g. delete a file will freeze mrl - only resolvable by killing the java task.

**Comment by supertick** [comment]
I do file -> open 
dialog appears
i delete file within dialog
it queries (are you sure?)
yes == delete 
worky for me on windows x64

cannot replicate - can you test again juerg

**Comment by juergmaier** [comment]
Played around with it for a while (rename, delete, open editor) and it did not block again. Consider it solved.
