### ISSUE TITLE
WebkitSpeech is crazy ( 3 same msg sent )

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#82]
Since last commit about msg ( I think )  webkitspeech send 3 same events at the same time.
Strange 

**09:18:06.678** [New I/O worker #8] INFO c.m.f.Service [WebkitSpeechRecognition.java:126] Recognized : >hello<
**09:18:06.679** [New I/O worker #8] INFO c.m.f.Service [WebkitSpeechRecognition.java:126] Recognized : >hello<
**09:18:06.680** [New I/O worker #8] INFO c.m.f.Service [WebkitSpeechRecognition.java:126] Recognized : >hello<

**Comment by supertick** [comment]
Yikes ! Ok, I'll check i out.

**Comment by supertick** [comment]
Thanks !
Had to do with refactoring the WebGui - silly mistake - fixed

**Comment by moz4r** [comment]
I was stucked on a same mistake some days ago, I didnt know we need to set a break Inside each case condition.
thank again !
