### ISSUE TITLE
Merge MimicSpeech into LocalSpeech

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#868]
#867 will give LocalSpeech the ability to use command templates to activate local TTS executable.

At the moment the PR is only for LocalSpeech Linux, and should be expanded in general for any of the operating systems.

"Perhaps" the mimic.exe from MimicSpeech should be bundled with LocalSpeech, and MimicSpeech removed. 
If mimic.exe stays, it should be bundled and deployed appropriately (not in the root mrl directory)

Local file caching filenames should take into account the template used - otherwise festival, espeak, or mimic might conflict with one another - (someone could end up mixing them unintentionally)

**Comment by Cyber-One** [comment]
The service page can then hold a list of known worky templates for different TTS systems and the OS they are used on and even how to install them.

**Comment by kwatters** [comment]
If we expect people to install it themselves, they will get it wrong and we will have to answer the question of why it doesn't work.

**Comment by Cyber-One** [comment]
That's where documentation come in, if the instruction on how to do it are there and clear, then a lot will work it out.
If you limit it to just what is installed by MRL, then you limit what can be done with MRL and you need to have a solution for a number of different systems.
That seems like a lot more development work.

**Comment by kwatters** [comment]
the template needs to be included in the cached wav file filename.  Otherwise, changing templates would be using the wrong cached file.
