### ISSUE TITLE
Ear WebGui Borked

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#87]
Ear's WebGui displays empty 
- Tested with -  InMoov Deep V3 scripts

**Comment by moz4r** [comment]
I confirm, it seem wide issue, whole WebGui seem borked. tested whith http://localhost:8888/#/service/chatBot , blank page too

**Comment by supertick** [comment]
I'm on it !

**Comment by supertick** [comment]
Temporarily fixed ...  it works BUT this part still needs refactoring.   I've made it go through its twisted logic to give it the same behavior as before.
This is to aid others, so they can test other aspects of MRL.
This STILL NEEDS REFACTORING - so I'm keeping the ticket open.

**Comment by supertick** [comment]
refactored and fixed
