### ISSUE TITLE
setMaxSpeed - must be re-entrant

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#874]
Must be re-entrant in that regardless of when setSpeed is set - the outcome should be the same .... not sure, but I don't think it is...

**Comment by kwatters** [comment]
maxspeed should be removed.

**Comment by kwatters** [comment]
as far as I can tell there is only 1 remaining reference to setMaxSpeed in the inmoov head python scripts for inmoov2 repo.

**Comment by hairygael** [comment]
Thanks, I missed that one, I will comment it out now that we've decided to remove setMaxSpeed.

**Comment by supertick** [comment]
so remove from AbstractServo now ?

**Comment by hairygael** [comment]
I guess so

**Comment by supertick** [comment]
removed in #911
