### ISSUE TITLE
Create "Another" configuration system

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#877]
Create another configuration system using config POJOs and yaml :P

**Comment by kwatters** [comment]
Why yaml?  How about json so it's easy for the webgui to work with...

**Comment by supertick** [comment]
I was thinking primarily as a replacement of the file based "ini" ...
yaml is a superset of json .. the pojo representation in either should be a tight one to one correspondence.
For file based configuration I prefer yaml in that it supports comments - export to json should be as easy as a single switch
