### ISSUE TITLE
face recognizer freezes

### ISSUE THREAD

**Issue by hairygael** [MyRobotLab/myrobotlab#89]
Hello guys.
I think it freezes since we have sub folders in the Training directory.
I'm using this python command, and I tried different options.
https://github.com/MyRobotLab/inmoov/blob/develop/InMoov/gestures/facerecognizer.py

When I comment
```
fr=i01.opencv.addFilter("FaceRecognizer")
fr.train()
```
it doesn't freeze anymore but of course it doesn't recognize the faces anymore.

**Comment by kwatters** [comment]
What's in your training folder?  Are you starting with a training set?  The training images will need to be moved into subfolders for each person.

**Comment by hairygael** [comment]
Hello Kevin,
Subfolders are created correctly and each subfolder has the name and
contains the various pictures of the person.
Myrobotlab/Training/Gael/pictures
All that works fine.
The freezing is an issue that Dominique has encountered as well.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-06-28 0:49 GMT+02:00 Kevin Watters <notifications@github.com>:

**Comment by supertick** [comment]
Can this be reproduced ?  What are the steps ?

**Comment by moz4r** [comment]
Fresh test of faceRecognizer, it seem Cascade Classifiers wont do the job
Is it worky for you guys ?  Off course I tested other things that the monkey

![image](https://user-images.githubusercontent.com/18124594/30939920-7c101d80-a3df-11e7-8cae-b4b1084aa314.png)

`opencv = Runtime.start("opencv","OpenCV")`
`opencv.captureFromImageFile("monkey.jpg")  `
`opencv.capture()  `
`opencv.addFilter("FaceRecognizer")  `
`opencv.setDisplayFilter("FaceRecognizer")  `
`fr= opencv.getFilter("FaceRecognizer")  `
`fr.train()`

**Comment by hairygael** [comment]
I tested last night very briefly with version MRL 2556. Face recognizer
recognized me correctly, but I didn't try to add someone new to see if the
clasifier was parsing correctly. My training folder already contains about
8 trained folder of people.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-09-28 0:02 GMT+02:00 Anthony <notifications@github.com>:
