### ISSUE TITLE
MrlComm fails to compile on the Leonardo

### ISSUE THREAD

**Issue by kwatters** [MyRobotLab/myrobotlab#891]
Setting Arduino IDE to build for the Leonardo and the following errors occur:

```
C:\dev\workspace.mrl4\myrobotlab\src\main\resources\resource\Arduino\MrlComm\MrlComm.ino: In function 'void setup()':

MrlComm:100: error: no matching function for call to 'MrlComm::begin(Serial_&)'

   mrlComm.begin(Serial);

                       ^

C:\dev\workspace.mrl4\myrobotlab\src\main\resources\resource\Arduino\MrlComm\MrlComm.ino:100:23: note: candidate is:

In file included from C:\dev\workspace.mrl4\myrobotlab\src\main\resources\resource\Arduino\MrlComm\MrlComm.ino:53:0:

sketch\MrlComm.h:192:8: note: void MrlComm::begin(HardwareSerial&)

   void begin(HardwareSerial &serial);

        ^

sketch\MrlComm.h:192:8: note:   no known conversion for argument 1 from 'Serial_' to 'HardwareSerial&'

exit status 1
no matching function for call to 'MrlComm::begin(Serial_&)'
```

**Comment by kwatters** [comment]
First item is we can fix this compilation error...  it requires some type casting in a few places.


```
HardwareSerial *hardwareSerial = (HardwareSerial*) &(Serial);
mrlComm.begin(*hardwareSerial);
```
Also the MrlSerialRelay needs a similar fix..

but once we do that, the resulting sketch is too large for the leonardo.  

I discovered that we can get back some image size by removing the msg->publishDebug messages  and removing the MrlNeoPixel support...  After doing that, MrlComm does compile and is small enough to run on the Leonardo...

I guess the real question is, how do we want to manage the size of the MrlComm sketch when it's built.  As it is now, if it grows to support more stuff, we'll loose support for boards like the Uno and the Leonardo.

**Comment by supertick** [comment]
I'd say Uno Mega & Esp8226/Esp32 would be the most important targets

**Comment by supertick** [comment]
I don't have an Leonardo, so I cannot test this

**Comment by kwatters** [comment]
you can reproduce this if you just set the target board to be the leonardo when you compile in the Arduino ide...  
I'm surprised that there are differences in these APIs across the various arduino board types.. But as mentioned, before even if we fix those issues, the mrlcomm sketch (I think) is still too big to run on the leonardo.

**Comment by supertick** [comment]
Well, if there is no motivation to fix it ... we shouldn't have this open ticket...
closing...
