### ISSUE TITLE
WebGui Slowness

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#898]
The webgui has 10 sec latency delay where a button is pressed.
Please help identify when and how these conditions can be replicated so it can be solved.

**Comment by kwatters** [comment]
I suspect this is related to lower bandwidth environments or lower cpu/memory platforms... at some point Ithink MRL is publishing too much data to the browser causing it to really slow down.

**Comment by supertick** [comment]
I agree - but which is it and what platforms ?
I run a raspi3 on a fast network - I haven't noticed such problems.
There could be areas of network communication which could be optimized, but it would be helpful to know in what context.

**Comment by supertick** [comment]
fixed
