### ISSUE TITLE
OpenNI - crashes

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#95]

**Comment by kwatters** [comment]
OpenNI is borked in Nixie at the moment due to us not pulling down the natives for it..  we can add the natives easy enough, however I think there are still issues beyond that for getting OpenNI to work.    Perhaps we move this to ogre afrer we fix the dependency problems.

**Comment by kwatters** [comment]
I just tried the latest, I believe this is fixed now.  I was able to do the install all, then start the openni service.  I clicked capture from the swing gui.  I saw the depth map start to display and my skeleton was being tracked and displayed as I stood in front of the kinect.   closing.
