### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#96]
![missing-journalist-body](https://user-images.githubusercontent.com/18124594/28480694-2e5b247a-6e62-11e7-9083-0a179ee9f05b.gif)

Long time I saw @Calamity01 I hope everything is ok for him. 
Look forward the day Inmoov will catch a beer in front or him with dl4j and next stage, ik computation.
See you dude ;)

**Comment by supertick** [comment]
I see his name drift through the shoutbox occasionally, hope he's doing well

**Comment by moz4r** [comment]
Found him, goodtime !! ![20180818_130628](https://user-images.githubusercontent.com/18124594/44301843-f9fe3180-a2eb-11e8-8d74-71e14da7a31e.jpg)

**Comment by Calamity01** [comment]
LOL... very good time indeed :)

**Comment by kwatters** [comment]
Awesome!  Calamity, if you are around in mid October, I will be in Montreal, would love to catch up!

**Comment by supertick** [comment]
I'm hoping I'll be there too ! ..
I know I'm in good company when the people around me use github for facebooking ;)

**Comment by Calamity01** [comment]
It will be great to meet you :)

**Comment by hairygael** [comment]
Great to see you Calamity!
I see Anthony got his MyRobotLab T-shirt and brought you the InMoov hat.
:)

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>




Le mar. 21 août 2018 à 13:14, Calamity01 <notifications@github.com> a
écrit :
