### ISSUE TITLE
OpenCV at Nixie 1.1.621 can NOT open file

### ISSUE THREAD

**Issue by Tricia279** [MyRobotLab/myrobotlab#976]
One thing is now good at Nixie 621, you can get a eg JPG-file from the file system :)

But when you choose a file, it would not open in the chrome browser. 
Therefore you can not use OpenCV to work with or on it :(

**Comment by supertick** [comment]
This works - in the webui when webui viewer is selected
![webui](https://user-images.githubusercontent.com/1266144/178093229-125fa1a5-95bb-4f1a-a5d1-ffa796ea062c.gif)
