### ISSUE TITLE
No velocity inside virtual arduino

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#99]
velocity seem like always = -1 if using virtual arduino

**Comment by moz4r** [comment]
I didnt found how to fix it. someone have an idea ?

**Comment by supertick** [comment]
I tested this - I can see when setting Velocity = 3 in SwingGui
[servo] INFO  c.myrobotlab.framework.Service - servoSetVelocity servo id 1 velocity 3
and virtual MrlServo's velocity becomes 3

Perhaps I'm not seeing the issue ?  Can you describe it more moz4r ?

**Comment by moz4r** [comment]
Video will explain ! 

Virtual world : https://youtu.be/Xx9lIE1yRGs
Real world : https://youtu.be/363NrwflIWs

**Comment by hairygael** [comment]
Great video Anthony,
I was also wondering if it was an issue with only my virtual InMoov or a
general issue.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-08-28 20:11 GMT+02:00 Anthony <notifications@github.com>:

**Comment by supertick** [comment]
Ah .. I see .. thanks for the video - makes sense now

**Comment by moz4r** [comment]
Hi Grog, do you think this can be fixed easily ? This will be very useful Inside test environment

**Comment by moz4r** [comment]
waiting cleaner things , I asked i01.left / i01.right to use i2Ccontroller connected on a fake raspi service in virtual mode.
with the help of last servocontroller interface changes inside inmoov . worky !
Not perfect because velocity(-1) in virtual world is very fast, but better than today !
